apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: video-platform
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -U app -d video; do
                echo "Waiting for postgres..."
                sleep 2
              done
      containers:
        - name: migrate
          image: riturroy/myvideoapp-api:latest
          command: ["sh", "-c", "cd /app/apps/api && npx prisma migrate deploy"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret